name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set script permissions
      run: chmod +x 1.Testing/script/run-integration.sh


    - name: Copy .env.example to .env
      run: cp ./1.Testing/.env.example ./1.Testing/.env

    - name: Run integration script
      run: cd 1.Testing && npm run test:integration
